### ISSUE TITLE
Mise en place de l'API REST

### ISSUE THREAD

**Issue by AlxisHenry** [Restiloc/api#2]
- [x] Mettre en place l'authentification
 - [x] Création du token d'accès et gestion des droits
 - [x] Création des controllers
 - [x] Gestion des valisations
 - [x] Créer les resources
 - [x] Rélations dans les resources
 - [x] Mise en place des routes d'API

**Comment by Vladimir9595** [comment]
Création des controllers
Créer les resources
Mise en place des routes d'API

done

**Comment by Vladimir9595** [comment]
Mettre en place l'authentification
Création du token d'accès et gestion des droits

done

**Comment by Vladimir9595** [comment]
Création des controllers
Gestion des valisations
Créer les resources
Rélations dans les resources

done
