### ISSUE TITLE
Base de données

### ISSUE THREAD

**Issue by AlxisHenry** [Restiloc/api#3]
- [x] Schéma MCD de la base de données
- [x] Mise en place des migrations
- [x] Mise en place des models
- [x] Mise en place des seeds
- [x] Récupération de fausses données concernant les véhicules à l'aide du site [myfakeapi.com](https://myfakeapi.com/api/cars/)
- [x] Créer une vue VehiculeExpertise

**Comment by Vladimir9595** [comment]
Schéma MCD de la base de données
Mise en place des migrations
Mise en place des models

done

**Comment by Vladimir9595** [comment]
Mise en place des seeds
Créer une vue VehiculeExpertise

done
